/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.AirlineDirectory;
import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightScheduleDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team Void
 */

    
public class FlightGoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightGoJPanel
     */
    
    private AirlineDirectory airlinedirectory;
    private JPanel rightPanel; 
    private CustomerDirectory customerDirectory;
    private FlightScheduleDirectory flightScheduleDirectory ;
    private ArrayList<Flight> search;

    
    
    public FlightGoJPanel(JPanel rightPanel, FlightScheduleDirectory flightScheduleDirectory, ArrayList<Flight> search, CustomerDirectory customerDirectory) 
    {
        initComponents();
        this.rightPanel =  rightPanel;
        this.flightScheduleDirectory = flightScheduleDirectory;
        this.search = search;
        this.customerDirectory = customerDirectory;
        populate();
    }

     private void populate() 
     {
         
        DefaultTableModel dtm = (DefaultTableModel) tblSortTable.getModel();
        dtm.setRowCount(0);
        for( Flight f: search)
        {
            Object[] row = new Object[9];
            row[0] = f;
            row[1] = f.getFlightNumber();
            row[2] = f.getSource();
            row[3] = f.getDepartureTime();
            row[4] = f.getDestination();
            row[5] = f.getArrivalTime();
            row[6] = f.getDuration();
            row[7] = f.getDate();
            row[8] = f.getPrice();
            
            dtm.addRow(row);   
            
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnSortByFare = new javax.swing.JButton();
        btnSortByDuration = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSortTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Flight Available");

        btnBook.setBackground(new java.awt.Color(0, 0, 0));
        btnBook.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnBook.setForeground(new java.awt.Color(204, 153, 255));
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        btnSortByFare.setBackground(new java.awt.Color(0, 0, 0));
        btnSortByFare.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSortByFare.setForeground(new java.awt.Color(204, 153, 255));
        btnSortByFare.setText("Cheapest Flight");
        btnSortByFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByFareActionPerformed(evt);
            }
        });

        btnSortByDuration.setBackground(new java.awt.Color(0, 0, 0));
        btnSortByDuration.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSortByDuration.setForeground(new java.awt.Color(204, 153, 255));
        btnSortByDuration.setText("Fastest Flight");
        btnSortByDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByDurationActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 153, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblSortTable.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        tblSortTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Flight Number", "Source", "Departure Time", "Destination", "Arrival Time", "Duration", "Date", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblSortTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSortByDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortByFare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSortByFare, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSortByDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        
        int selectedRow = tblSortTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select a flight for booking","warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            
        Flight flight = (Flight) tblSortTable.getValueAt(selectedRow,0);
        BookFlightJPanel bookFlightJPanel = new BookFlightJPanel(rightPanel,flight, customerDirectory, flightScheduleDirectory, airlinedirectory);
        rightPanel.add("BookFlightJPanel",bookFlightJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

        }
 
        /*BookFlightJPanel bookpanel = new BookFlightJPanel(rightPanel, flight, customerDirectory, flightScheduleDirectory, airlinedirectory);
        rightPanel.add("BookFlightJPanel",bookpanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel); */
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnSortByDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByDurationActionPerformed
 
            ArrayList<Flight> t = search;

            int a = search.size();
            int len = search.size()-1;
                
            for (int i = 0; i < len; i++){   
      
            for (int j = 0; j < a-i-1; j++)  
       
          if (t.get(j).getDuration() > t.get(j+1).getDuration()) 
                { 
                    
                    Flight fl = t.get(j);
                    t.set(j, t.get(j+1));
                    t.set(j+1, fl);
                    
                }
            }
            
        DefaultTableModel dtm = (DefaultTableModel) tblSortTable.getModel();
        dtm.setRowCount(0);
        for( Flight f: t)
        {
            Object[] row = new Object[9];
            row[0] = f;
            row[1] = f.getFlightNumber();
            row[2] = f.getSource();
            row[3] = f.getDepartureTime();
            row[4] = f.getDestination();
            row[5] = f.getArrivalTime();
            row[6] = f.getDuration();
            row[7] = f.getDate();
            row[8] = f.getPrice();
            
            dtm.addRow(row);   
        }
    }//GEN-LAST:event_btnSortByDurationActionPerformed

    private void btnSortByFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByFareActionPerformed
        
        
            ArrayList<Flight> t = search;

            int a = search.size();
            int len = search.size()-1;
                
            for (int i = 0; i < len; i++){   
      
            for (int j = 0; j < a-i-1; j++)  
       
          if (t.get(j).getPrice() > t.get(j+1).getPrice()) 
                { 
                    
                    Flight fl = t.get(j);
                    t.set(j, t.get(j+1));
                    t.set(j+1, fl);
                    
                }
            }
            
        DefaultTableModel dtm = (DefaultTableModel) tblSortTable.getModel();
        dtm.setRowCount(0);
        for( Flight f: t)
        {
            Object[] row = new Object[9];
            row[0] = f;
            row[1] = f.getFlightNumber();
            row[2] = f.getSource();
            row[3] = f.getDepartureTime();
            row[4] = f.getDestination();
            row[5] = f.getArrivalTime();
            row[6] = f.getDuration();
            row[7] = f.getDate();
            row[8] = f.getPrice();
            
            dtm.addRow(row);   
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnSortByFareActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnSortByDuration;
    private javax.swing.JButton btnSortByFare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSortTable;
    // End of variables declaration//GEN-END:variables

   
}
