/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.AirlineDirectory;
import Business.Airliner;
import Business.Customer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team Void
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    private AirlineDirectory airlinedirectory;
    private JPanel rightPanel;
    
    
    
    
    public ManageAirlinersJPanel(JPanel rightPanel, AirlineDirectory airlinedirectory) {
        initComponents();
        this.rightPanel = rightPanel;
        this.airlinedirectory = airlinedirectory;
        populate();
    }

    private void populate() {
        DefaultTableModel dtm = (DefaultTableModel) tblManageAirliners.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a: airlinedirectory.getAirlineList()){
            System.out.println(airlinedirectory.getAirlineList());
            Object[] row = new Object[3];
            row[0] = a;
            row[1] = a.getAirlinerAddress();
            row[2] = a.getTotalFlightsPerDay();
         
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageAirliners = new javax.swing.JTable();
        btnAddAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnDeleteAirliner = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 153, 255));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Master Airliner Schedule");

        tblManageAirliners.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        tblManageAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Airliner Country", "Flights Per Day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageAirliners);

        btnAddAirliner.setBackground(new java.awt.Color(0, 0, 0));
        btnAddAirliner.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnAddAirliner.setForeground(new java.awt.Color(204, 153, 255));
        btnAddAirliner.setText("Add Airliner");
        btnAddAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAirliner.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnViewAirliner.setForeground(new java.awt.Color(204, 153, 255));
        btnViewAirliner.setText("Update Record");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnDeleteAirliner.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteAirliner.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnDeleteAirliner.setForeground(new java.awt.Color(204, 153, 255));
        btnDeleteAirliner.setText("Delete Airliner");
        btnDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlinerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAddAirliner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewAirliner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlinerActionPerformed
        
        CreateNewAirlinerJPanel managePanel = new CreateNewAirlinerJPanel(rightPanel, airlinedirectory);
        rightPanel.add("CreateNewAirlinerJPanel",managePanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnAddAirlinerActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        int selectedRow = tblManageAirliners.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select a Row from table first","warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        Airliner airliner = (Airliner) tblManageAirliners.getValueAt(selectedRow,0);
        ViewAirlinerJPanel viewpanel = new ViewAirlinerJPanel(rightPanel, airliner, airlinedirectory);
        rightPanel.add("ViewAirlinerJPanel",viewpanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        }
        
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlinerActionPerformed
        
         int selectedRow = tblManageAirliners.getSelectedRow();
        
        if(selectedRow>=0){
            
            int dialogButton = JOptionPane.YES_NO_OPTION;     
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the selected airliner", "Warning", dialogButton);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                
                Airliner a = (Airliner) tblManageAirliners.getValueAt(selectedRow, 0);
                airlinedirectory.deleteAirliner(a);
              
                populate();
            } 
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a booking history from table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirliner;
    private javax.swing.JButton btnDeleteAirliner;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageAirliners;
    // End of variables declaration//GEN-END:variables

    
}
