/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.AirlineDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import Business.FlightScheduleDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team Void
 */
public class RecentBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecentBookingJPanel
     */
    
    private FlightScheduleDirectory flightScheduleDirectory;
    private AirlineDirectory airlineDirectory;
    private JPanel rightPanel;
    private CustomerDirectory customerDirectory;

    public RecentBookingJPanel(JPanel rightPanel, CustomerDirectory customerDirectory, FlightScheduleDirectory flightScheduleDirectory,AirlineDirectory airlinedirectory) {
        
        initComponents();
        this.rightPanel = rightPanel;
        this.airlineDirectory = airlinedirectory;
        this.flightScheduleDirectory = flightScheduleDirectory;
        this.customerDirectory = customerDirectory;
        populate();
    }
    
    private void populate() {
        
        
        DefaultTableModel dtm = (DefaultTableModel)tblBookingDetails.getModel();
        dtm.setRowCount(0);
        for (Customer c: customerDirectory.getCustomerList())
        {
          Object[] row = new Object[11];
          row[0] =c;
          row[1] =c.getCustLastName();
          row[2] =c.getCustPassportNo(); 
          row[3] =c.getCustEmailID();
          row[4] =c.getAirlineName();
          row[5] =c.getCustFlightno();
          row[6] =c.getCustSource();
          row[7] =c.getCustDestination();
          row[8] =c.getCustDepTime();
          row[9] =c.getCustArrTime();
          row[10] =c.getCustSeatNo();

 
          dtm.addRow(row);
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookingDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(204, 153, 255));

        tblBookingDetails.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        tblBookingDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Passport Number", "Email ID", "Airliner Name", "Flight Number", "Source", "Destination", "Departure Time", "Arrival Time", "Seat Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBookingDetails);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setText("Customer Booking History");

        btnCancel.setBackground(new java.awt.Color(0, 0, 0));
        btnCancel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(204, 153, 255));
        btnCancel.setText("Cancel Booking");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

          int selectedRow = tblBookingDetails.getSelectedRow();
        
        if(selectedRow>=0){
            
            int dialogButton = JOptionPane.YES_NO_OPTION;     
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the selected booking", "Warning", dialogButton);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                
                Customer c = (Customer) tblBookingDetails.getValueAt(selectedRow, 0);
                customerDirectory.deleteCCustomer(c);
              
                populate();
            } 
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a booking history from table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnCancelActionPerformed

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBookingDetails;
    // End of variables declaration//GEN-END:variables
}
