/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.AirlineDirectory;
import Business.CustomerDirectory;
import Business.Flight;
import Business.FlightScheduleDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Team Void
 */
public class SearchFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlightJPanel
     */
    private AirlineDirectory airlineDirectory;
    private FlightScheduleDirectory flightScheduleDirectory;
    private JPanel rightPanel;
    private CustomerDirectory customerDirectory;
    
    public SearchFlightJPanel(JPanel rightPanel, FlightScheduleDirectory flightScheduleDirectory, AirlineDirectory airlineDirectory, CustomerDirectory customerDirectory) {
        
        initComponents();
        this.airlineDirectory=airlineDirectory;
        this.flightScheduleDirectory = flightScheduleDirectory;
        this.rightPanel = rightPanel;
        this.customerDirectory = customerDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGo = new javax.swing.JButton();
        txtSource = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTravelDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 153, 255));

        btnGo.setBackground(new java.awt.Color(0, 0, 0));
        btnGo.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnGo.setForeground(new java.awt.Color(204, 153, 255));
        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel3.setText("Destination");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel4.setText("Travel Date");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel5.setText("SEARCH YOUR FLIGHT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSource, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtTravelDate))
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTravelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(430, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        
        if(txtSource.getText().equals("") || txtSource.getText() == null){
            
            JOptionPane.showMessageDialog(null, "Kindly Enter Source Location", "Warning",JOptionPane.WARNING_MESSAGE);   
            return;
        
        }
        
        if(txtDestination.getText().equals("") || txtDestination.getText() == null){
            
           JOptionPane.showMessageDialog(null, "Kindly Enter Destination Location", "Warning",JOptionPane.WARNING_MESSAGE);    
           return;
        }
        
        
        if(txtTravelDate.getText().equals("") || txtTravelDate.getText() == null){
            
            JOptionPane.showMessageDialog(null, "Kindly Enter Travel Date", "Warning",JOptionPane.WARNING_MESSAGE);   
            return;
       }
        else {
        
         if(!DatePatternCorrect()){
        
         JOptionPane.showMessageDialog(null, "Date should be in the form DD/MM/YYYY", "Warning",JOptionPane.WARNING_MESSAGE);   
         return;
        }
        }
        

        String source1= txtSource.getText();
        String destination1 = txtDestination.getText();
        String date = txtTravelDate.getText();
        
        ArrayList<Flight> searchflight = flightScheduleDirectory.getAvailableFlightList(source1, destination1, date);

        if(searchflight.isEmpty()){
            JOptionPane.showMessageDialog(null, "No Flights Available");
        }
        else{
            
        FlightGoJPanel gopanel = new FlightGoJPanel(rightPanel, flightScheduleDirectory , searchflight, customerDirectory);
        rightPanel.add("FlightGoJPanel",gopanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        }
      
        txtDestination.setText("");
        txtSource.setText("");
        txtTravelDate.setText("");
        
    }//GEN-LAST:event_btnGoActionPerformed

    private boolean DatePatternCorrect() {
       
       Pattern p = Pattern.compile("^[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{4}$");
       Matcher m = p.matcher(txtTravelDate.getText());
       boolean b = m.matches();
       return b;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTravelDate;
    // End of variables declaration//GEN-END:variables

    
}
