/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Logic.Car;
import Logic.CarInformationList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Tanvi Gurav
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private ArrayList<Car> carList;
    
    public MainJFrame() {
      initComponents();
      carList = CarInformationList.getCarList().carList;
        for(Car c:carList)
            System.out.println(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        displayContainer = new javax.swing.JPanel();
        mainMenuContainer = new javax.swing.JPanel();
        btnAcctManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayContainer.setBackground(new java.awt.Color(102, 102, 0));
        displayContainer.setLayout(new java.awt.CardLayout());
        mainSplitPane.setRightComponent(displayContainer);

        mainMenuContainer.setBackground(new java.awt.Color(102, 102, 0));

        btnAcctManager.setBackground(new java.awt.Color(255, 204, 0));
        btnAcctManager.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnAcctManager.setText("Account Manager");
        btnAcctManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcctManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainMenuContainerLayout = new javax.swing.GroupLayout(mainMenuContainer);
        mainMenuContainer.setLayout(mainMenuContainerLayout);
        mainMenuContainerLayout.setHorizontalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAcctManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainMenuContainerLayout.setVerticalGroup(
            mainMenuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuContainerLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnAcctManager, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        mainSplitPane.setLeftComponent(mainMenuContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSplitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcctManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcctManagerActionPerformed
        
        WorkAreaJPanel panel = new WorkAreaJPanel(displayContainer, carList);
        displayContainer.add("WorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) displayContainer.getLayout();
        layout.next(displayContainer);

    }//GEN-LAST:event_btnAcctManagerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcctManager;
    private javax.swing.JPanel displayContainer;
    private javax.swing.JPanel mainMenuContainer;
    private javax.swing.JSplitPane mainSplitPane;
    // End of variables declaration//GEN-END:variables
}
