/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Logic.Car;
import Logic.CarInformationList;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tanvi Gurav
 */
public class UpdateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
 
    private JPanel displayContainer;
  //  private List<Car> carList;
    private Car c;
    
    public UpdateAccountJPanel(JPanel displayContainer, Car c) {
        
        initComponents();
         
        this.displayContainer = displayContainer;
        this.c = c;
        populateCarDetails();
        //btnSave.setEnabled(false);
      
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtFieldBrand = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFieldModelNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldSerialNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldAvailability = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldMaxSeats = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFieldMinSeats = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFieldManuYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFieldCertiDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboAvailability = new javax.swing.JComboBox<>();
        comboMaintainCerti = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 102, 0));

        btnBack.setBackground(new java.awt.Color(255, 204, 0));
        btnBack.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Update Car Details");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Brand");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Model Number");

        txtFieldAvailability.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Serial Number");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Availability");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Available City");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Maximum Seats");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Minimum Seats");

        txtFieldCertiDate.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Manufactured Year");

        btnSave.setBackground(new java.awt.Color(255, 204, 0));
        btnSave.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("Maintainence Certificate Validity");

        comboAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        comboMaintainCerti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFieldBrand)
                                    .addComponent(txtFieldModelNum)
                                    .addComponent(txtFieldSerialNum)
                                    .addComponent(txtFieldCity)
                                    .addComponent(txtFieldMaxSeats)
                                    .addComponent(txtFieldMinSeats)
                                    .addComponent(txtFieldManuYear)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldAvailability))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboMaintainCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFieldCertiDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(1, 1, 1))
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFieldModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldSerialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFieldMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFieldMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFieldManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFieldCertiDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMaintainCerti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void populateCarDetails(){
        
        txtFieldAvailability.setText(String.valueOf(c.isAvailable()));
        txtFieldBrand.setText(c.getBrand());
        txtFieldManuYear.setText(String.valueOf(c.getManufactured_year()));
        txtFieldMinSeats.setText(String.valueOf(c.getMin_seats()));
        txtFieldMaxSeats.setText(String.valueOf(c.getMax_seats()));
        txtFieldSerialNum.setText(String.valueOf(c.getSerial_num()));
        txtFieldModelNum.setText(c.getModel_num());
        txtFieldCity.setText(c.getAvailble_city());
        txtFieldCertiDate.setText(String.valueOf(c.isMaintenance_certificate()));  
    }
        
        
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
       
       displayContainer.remove(this);
       CardLayout layout = (CardLayout) displayContainer.getLayout();
       layout.previous(displayContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    //**********************Handling Exceptions************************************
    
    String b = txtFieldBrand.getText() ;
     if(b == null || b.equals("")){
               JOptionPane.showMessageDialog(null, "Brand Can't be Empty!");
               return;
           }

    String model = txtFieldModelNum.getText() ;
     if(model == null || model.equals("")){
               JOptionPane.showMessageDialog(null, "Model Number Can't be Empty!");
               return;
           }
    
    String serial = txtFieldSerialNum.getText();
    try{  
              Integer.parseInt(serial);
           }catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "Enter valid Serial Number");
              return;
           }
    
    String city = txtFieldCity.getText() ;
     if(city == null || city.equals("")){
               JOptionPane.showMessageDialog(null, "City Can't be Empty!");
               return;
           }
     
    String max = txtFieldMaxSeats.getText();
    try{  
              Integer.parseInt(max);
           }catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "Enter valid Seats");
              return;
           }
    
    String min = txtFieldMinSeats.getText();
    try{  
              Integer.parseInt(min);
           }catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "Enter valid Seats");
              return;
           }

    String year = txtFieldManuYear.getText();
    try{  
              Integer.parseInt(year);
           }catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "Enter a valid Manufactured Year");
              return;
           }
    
     
        c.setAvailable(Boolean.parseBoolean(txtFieldAvailability.getText()));
        c.setBrand(txtFieldBrand.getText());
        c.setManufactured_year(Integer.parseInt(txtFieldManuYear.getText()));
        c.setMin_seats(Integer.parseInt(txtFieldMinSeats.getText()));
        c.setMax_seats(Integer.parseInt(txtFieldMaxSeats.getText()));
        c.setSerial_num(Integer.parseInt(txtFieldSerialNum.getText()));
        c.setModel_num(txtFieldModelNum.getText());
        c.setAvailble_city(txtFieldCity.getText());
        c.setMaintenance_certificate(Boolean.parseBoolean(txtFieldCertiDate.getText()));
      
       // btnSave.setEnabled(true);
        CarInformationList.setDate();
        JOptionPane.showMessageDialog(null, "Account updated successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboAvailability;
    private javax.swing.JComboBox<String> comboMaintainCerti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFieldAvailability;
    private javax.swing.JTextField txtFieldBrand;
    private javax.swing.JTextField txtFieldCertiDate;
    private javax.swing.JTextField txtFieldCity;
    private javax.swing.JTextField txtFieldManuYear;
    private javax.swing.JTextField txtFieldMaxSeats;
    private javax.swing.JTextField txtFieldMinSeats;
    private javax.swing.JTextField txtFieldModelNum;
    private javax.swing.JTextField txtFieldSerialNum;
    // End of variables declaration//GEN-END:variables


}
