/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlineDirectory;
import Business.CustomerDirectory;
import Business.FlightScheduleDirectory;
import Business.Seat;
import UserInterface.ManageAirliners.FlightScheduleJPanel;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import UserInterface.ManageAirliners.RecentBookingJPanel;
import UserInterface.ManageAirliners.SearchFlightJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Team Void
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    
    private AirlineDirectory airlinedirectory;
    private FlightScheduleDirectory flightScheduleDirectory;
    private CustomerDirectory customerDirectory;
   // private Seat seat;
    //rivate Airliner airliner;
     
   
    
    
    public TravelAgencyMain() {
        initComponents();
        
        airlinedirectory = new AirlineDirectory();
        flightScheduleDirectory= new FlightScheduleDirectory();
        customerDirectory = new CustomerDirectory();
        //seat = new Seat();
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CardSequenceJPanel = new javax.swing.JPanel();
        btnManageAirliners = new javax.swing.JButton();
        btnSearchAirliners = new javax.swing.JButton();
        btnRecentBooking = new javax.swing.JButton();
        btnManageFlights1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CardSequenceJPanel.setBackground(new java.awt.Color(0, 0, 0));
        CardSequenceJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageAirliners.setBackground(new java.awt.Color(204, 153, 255));
        btnManageAirliners.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnManageAirliners.setText("Manage Airliners");
        btnManageAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinersActionPerformed(evt);
            }
        });
        CardSequenceJPanel.add(btnManageAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 40));

        btnSearchAirliners.setBackground(new java.awt.Color(204, 153, 255));
        btnSearchAirliners.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSearchAirliners.setText("Book Tickets");
        btnSearchAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAirlinersActionPerformed(evt);
            }
        });
        CardSequenceJPanel.add(btnSearchAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 40));

        btnRecentBooking.setBackground(new java.awt.Color(204, 153, 255));
        btnRecentBooking.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnRecentBooking.setText("Recent Bookings");
        btnRecentBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecentBookingActionPerformed(evt);
            }
        });
        CardSequenceJPanel.add(btnRecentBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 40));

        btnManageFlights1.setBackground(new java.awt.Color(204, 153, 255));
        btnManageFlights1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnManageFlights1.setText("Manage Flight");
        btnManageFlights1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlights1ActionPerformed(evt);
            }
        });
        CardSequenceJPanel.add(btnManageFlights1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 40));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setText("MENU");
        CardSequenceJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, -1));

        jSplitPane1.setLeftComponent(CardSequenceJPanel);

        rightPanel.setBackground(new java.awt.Color(204, 153, 255));
        rightPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinersActionPerformed
        // TODO add your handling code here:       
        ManageAirlinersJPanel managePanel = new ManageAirlinersJPanel(rightPanel, airlinedirectory);
        rightPanel.add("ManageAirlinersJPanel",managePanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnManageAirlinersActionPerformed

    private void btnSearchAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAirlinersActionPerformed
        
        SearchFlightJPanel searchpanel = new SearchFlightJPanel(rightPanel, flightScheduleDirectory, airlinedirectory, customerDirectory);
        rightPanel.add("SearchFlightJPanel",searchpanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        
        
    }//GEN-LAST:event_btnSearchAirlinersActionPerformed

    private void btnRecentBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecentBookingActionPerformed
          
        RecentBookingJPanel recentBookingJPanel = new RecentBookingJPanel(rightPanel, customerDirectory, flightScheduleDirectory,airlinedirectory);
        rightPanel.add("RecentBookingJPanel",recentBookingJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }//GEN-LAST:event_btnRecentBookingActionPerformed

    private void btnManageFlights1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlights1ActionPerformed
        
        FlightScheduleJPanel schedulepanel = new FlightScheduleJPanel(rightPanel, flightScheduleDirectory,airlinedirectory);
        rightPanel.add("FlightScheduleJPanel",schedulepanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }//GEN-LAST:event_btnManageFlights1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardSequenceJPanel;
    private javax.swing.JButton btnManageAirliners;
    private javax.swing.JButton btnManageFlights1;
    private javax.swing.JButton btnRecentBooking;
    private javax.swing.JButton btnSearchAirliners;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
